# Generated by Django 6.0.6 on 2026-06-25 07:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gym', '0005_alter_gym_options_alter_gymbanner_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام پلن')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('price', models.PositiveIntegerField(verbose_name='قیمت (تومان)')),
                ('duration_days', models.PositiveIntegerField(verbose_name='مدت اعتبار (روز)')),
                ('token_count', models.PositiveIntegerField(verbose_name='تعداد توکن')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('gyms', models.ManyToManyField(related_name='plans', to='gym.gym', verbose_name='باشگاه\u200cهای مجاز')),
            ],
            options={
                'verbose_name': 'پلن',
                'verbose_name_plural': 'پلن\u200cها',
                'ordering': ['order', 'price'],
            },
        ),
        migrations.CreateModel(
            name='UserDiscountProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accumulated_leftover_tokens', models.PositiveIntegerField(default=0, verbose_name='مجموع توکن\u200cهای باقیمانده')),
                ('discount_amount', models.PositiveIntegerField(default=0, verbose_name='مبلغ تخفیف (تومان)')),
                ('is_used', models.BooleanField(default=False, verbose_name='تخفیف استفاده شده')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین به\u200cروزرسانی')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='discount_profile', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پروفایل تخفیف',
                'verbose_name_plural': 'پروفایل\u200cهای تخفیف',
            },
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'فعال'), ('expired', 'منقضی\u200cشده'), ('cancelled', 'لغو\u200cشده')], default='active', max_length=20, verbose_name='وضعیت')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ شروع')),
                ('end_date', models.DateTimeField(verbose_name='تاریخ پایان')),
                ('tokens_total', models.PositiveIntegerField(verbose_name='کل توکن\u200cها')),
                ('tokens_used', models.PositiveIntegerField(default=0, verbose_name='توکن\u200cهای استفاده\u200cشده')),
                ('leftover_tokens', models.PositiveIntegerField(default=0, verbose_name='توکن\u200cهای باقیمانده هنگام انقضا')),
                ('paid_amount', models.PositiveIntegerField(verbose_name='مبلغ پرداختی (تومان)')),
                ('discount_applied', models.PositiveIntegerField(default=0, verbose_name='تخفیف اعمال\u200cشده (تومان)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ خرید')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='subscriptions.plan', verbose_name='پلن')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'اشتراک',
                'verbose_name_plural': 'اشتراک\u200cها',
                'ordering': ['-created_at'],
            },
        ),
    ]
