# Generated by Django 6.0.6 on 2026-06-20 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='نام باشگاه')),
                ('address', models.TextField(verbose_name='آدرس')),
                ('phone', models.CharField(max_length=20, verbose_name='شماره تماس')),
                ('latitude', models.FloatField(verbose_name='عرض جغرافیایی')),
                ('longitude', models.FloatField(verbose_name='طول جغرافیایی')),
                ('popularity_score', models.PositiveIntegerField(default=0, verbose_name='امتیاز محبوبیت')),
                ('is_popular', models.BooleanField(default=False, verbose_name='باشگاه محبوب')),
            ],
            options={
                'verbose_name': 'باشگاه',
                'verbose_name_plural': 'باشگاه\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام رشته ورزشی')),
            ],
            options={
                'verbose_name': 'رشته ورزشی',
                'verbose_name_plural': 'رشته\u200cهای ورزشی',
            },
        ),
        migrations.CreateModel(
            name='SportCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان دسته\u200cبندی')),
                ('slug', models.SlugField(unique=True, verbose_name='اسلاگ')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی ورزشی',
                'verbose_name_plural': 'دسته\u200cبندی\u200cهای ورزشی',
            },
        ),
        migrations.CreateModel(
            name='GymPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_price', models.PositiveIntegerField(verbose_name='قیمت ماهانه')),
                ('yearly_price', models.PositiveIntegerField(verbose_name='قیمت سالانه')),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='gym.gym', verbose_name='باشگاه')),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym.sport', verbose_name='رشته ورزشی')),
            ],
            options={
                'verbose_name': 'قیمت باشگاه',
                'verbose_name_plural': 'قیمت\u200cهای باشگاه',
            },
        ),
        migrations.AddField(
            model_name='gym',
            name='sports',
            field=models.ManyToManyField(related_name='gyms', to='gym.sport', verbose_name='رشته\u200cهای ورزشی'),
        ),
        migrations.AddField(
            model_name='sport',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sports', to='gym.sportcategory', verbose_name='دسته\u200cبندی'),
        ),
    ]
