# Generated by Django 6.0.6 on 2026-06-21 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='gyms/covers/', verbose_name='تصویر اصلی باشگاه'),
        ),
        migrations.CreateModel(
            name='GymImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gyms/gallery/', verbose_name='تصویر')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='عنوان تصویر')),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='gym.gym', verbose_name='باشگاه')),
            ],
            options={
                'verbose_name': 'تصویر باشگاه',
                'verbose_name_plural': 'تصاویر باشگاه',
            },
        ),
        migrations.CreateModel(
            name='GymVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.URLField(verbose_name='لینک ویدیو (YouTube/MP4)')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='عنوان ویدیو')),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='gym.gym', verbose_name='باشگاه')),
            ],
            options={
                'verbose_name': 'ویدیو باشگاه',
                'verbose_name_plural': 'ویدیوهای باشگاه',
            },
        ),
    ]
