# Generated by Django 6.0.6 on 2026-06-21 09:24

import gym.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0002_gym_cover_image_gymimage_gymvideo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gym',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to=gym.models.upload_gym_cover_image, verbose_name='تصویر اصلی باشگاه'),
        ),
    ]
