# Generated by Django 6.0.6 on 2026-06-22 09:43

import django.db.models.deletion
import gym.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0003_alter_gym_cover_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='GymFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='gym',
            options={},
        ),
        migrations.AlterModelOptions(
            name='gymimage',
            options={},
        ),
        migrations.AlterModelOptions(
            name='gymprice',
            options={},
        ),
        migrations.AlterModelOptions(
            name='gymvideo',
            options={},
        ),
        migrations.AlterModelOptions(
            name='sport',
            options={},
        ),
        migrations.AlterModelOptions(
            name='sportcategory',
            options={},
        ),
        migrations.AddField(
            model_name='gym',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='gym',
            name='instagram',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='gym',
            name='rules',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='gym',
            name='telegram',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='gym',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='gym',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='gym',
            name='working_hours',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='gymprice',
            name='quarterly_price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gymprice',
            name='session_price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gym',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='gym',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to=gym.models.upload_gym_cover_image),
        ),
        migrations.AlterField(
            model_name='gym',
            name='is_popular',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='gym',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='gym',
            name='longitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='gym',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='gym',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='gym',
            name='popularity_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gym',
            name='sports',
            field=models.ManyToManyField(related_name='gyms', to='gym.sport'),
        ),
        migrations.AlterField(
            model_name='gymimage',
            name='gym',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='gym.gym'),
        ),
        migrations.AlterField(
            model_name='gymimage',
            name='image',
            field=models.ImageField(upload_to='gyms/gallery/'),
        ),
        migrations.AlterField(
            model_name='gymimage',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='gymprice',
            name='gym',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='gym.gym'),
        ),
        migrations.AlterField(
            model_name='gymprice',
            name='monthly_price',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='gymprice',
            name='sport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym.sport'),
        ),
        migrations.AlterField(
            model_name='gymprice',
            name='yearly_price',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='gymvideo',
            name='gym',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='gym.gym'),
        ),
        migrations.AlterField(
            model_name='gymvideo',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='gymvideo',
            name='video_url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='sport',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sports', to='gym.sportcategory'),
        ),
        migrations.AlterField(
            model_name='sport',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sportcategory',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='sportcategory',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='GymBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gyms/banners/')),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banners', to='gym.gym')),
            ],
        ),
        migrations.CreateModel(
            name='GymCoach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='gyms/coaches/')),
                ('specialty', models.CharField(max_length=100)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coaches', to='gym.gym')),
            ],
        ),
        migrations.AddField(
            model_name='gym',
            name='facilities',
            field=models.ManyToManyField(blank=True, related_name='gyms', to='gym.gymfacility'),
        ),
        migrations.CreateModel(
            name='GymReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rating', models.PositiveSmallIntegerField(default=5)),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='gym.gym')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
