# Generated by Django 6.0.6 on 2026-06-22 09:43

import django.db.models.deletion
import gym.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0004_gymfacility_alter_gym_options_alter_gymimage_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gym',
            options={'verbose_name': 'باشگاه', 'verbose_name_plural': 'باشگاه\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='gymbanner',
            options={'verbose_name': 'بنر باشگاه', 'verbose_name_plural': 'بنرهای باشگاه'},
        ),
        migrations.AlterModelOptions(
            name='gymcoach',
            options={'verbose_name': 'مربی', 'verbose_name_plural': 'مربیان'},
        ),
        migrations.AlterModelOptions(
            name='gymfacility',
            options={'verbose_name': 'امکانات باشگاه', 'verbose_name_plural': 'امکانات باشگاه'},
        ),
        migrations.AlterModelOptions(
            name='gymimage',
            options={'verbose_name': 'تصویر باشگاه', 'verbose_name_plural': 'گالری تصاویر'},
        ),
        migrations.AlterModelOptions(
            name='gymprice',
            options={'verbose_name': 'تعرفه باشگاه', 'verbose_name_plural': 'تعرفه\u200cهای باشگاه'},
        ),
        migrations.AlterModelOptions(
            name='gymreview',
            options={'ordering': ['-created_at'], 'verbose_name': 'نظر کاربران', 'verbose_name_plural': 'نظرات کاربران'},
        ),
        migrations.AlterModelOptions(
            name='gymvideo',
            options={'verbose_name': 'ویدیو باشگاه', 'verbose_name_plural': 'ویدیوهای باشگاه'},
        ),
        migrations.AlterModelOptions(
            name='sport',
            options={'verbose_name': 'رشته ورزشی', 'verbose_name_plural': 'رشته\u200cهای ورزشی'},
        ),
        migrations.AlterModelOptions(
            name='sportcategory',
            options={'verbose_name': 'دسته\u200cبندی ورزشی', 'verbose_name_plural': 'دسته\u200cبندی\u200cهای ورزشی'},
        ),
        migrations.AlterField(
            model_name='gym',
            name='address',
            field=models.TextField(verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='gym',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to=gym.models.upload_gym_cover_image, verbose_name='تصویر اصلی باشگاه'),
        ),
        migrations.AlterField(
            model_name='gym',
            name='description',
            field=models.TextField(blank=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='gym',
            name='facilities',
            field=models.ManyToManyField(blank=True, related_name='gyms', to='gym.gymfacility', verbose_name='امکانات'),
        ),
        migrations.AlterField(
            model_name='gym',
            name='instagram',
            field=models.URLField(blank=True, verbose_name='لینک اینستاگرام'),
        ),
        migrations.AlterField(
            model_name='gym',
            name='is_popular',
            field=models.BooleanField(default=False, verbose_name='باشگاه محبوب'),
        ),
        migrations.AlterField(
            model_name='gym',
            name='latitude',
            field=models.FloatField(verbose_name='عرض جغرافیایی'),
        ),
        migrations.AlterField(
            model_name='gym',
            name='longitude',
            field=models.FloatField(verbose_name='طول جغرافیایی'),
        ),
        migrations.AlterField(
            model_name='gym',
            name='name',
            field=models.CharField(max_length=150, verbose_name='نام باشگاه'),
        ),
        migrations.AlterField(
            model_name='gym',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='شماره تماس'),
        ),
        migrations.AlterField(
            model_name='gym',
            name='popularity_score',
            field=models.PositiveIntegerField(default=0, verbose_name='امتیاز محبوبیت'),
        ),
        migrations.AlterField(
            model_name='gym',
            name='rules',
            field=models.TextField(blank=True, verbose_name='قوانین و مقررات'),
        ),
        migrations.AlterField(
            model_name='gym',
            name='sports',
            field=models.ManyToManyField(related_name='gyms', to='gym.sport', verbose_name='رشته\u200cهای ورزشی'),
        ),
        migrations.AlterField(
            model_name='gym',
            name='telegram',
            field=models.URLField(blank=True, verbose_name='لینک تلگرام'),
        ),
        migrations.AlterField(
            model_name='gym',
            name='website',
            field=models.URLField(blank=True, verbose_name='وب\u200cسایت'),
        ),
        migrations.AlterField(
            model_name='gym',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=20, verbose_name='شماره واتساپ'),
        ),
        migrations.AlterField(
            model_name='gym',
            name='working_hours',
            field=models.CharField(blank=True, max_length=255, verbose_name='ساعات کاری'),
        ),
        migrations.AlterField(
            model_name='gymbanner',
            name='gym',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banners', to='gym.gym', verbose_name='باشگاه'),
        ),
        migrations.AlterField(
            model_name='gymbanner',
            name='image',
            field=models.ImageField(upload_to='gyms/banners/', verbose_name='بنر'),
        ),
        migrations.AlterField(
            model_name='gymcoach',
            name='full_name',
            field=models.CharField(max_length=100, verbose_name='نام مربی'),
        ),
        migrations.AlterField(
            model_name='gymcoach',
            name='gym',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coaches', to='gym.gym', verbose_name='باشگاه'),
        ),
        migrations.AlterField(
            model_name='gymcoach',
            name='image',
            field=models.ImageField(upload_to='gyms/coaches/', verbose_name='تصویر مربی'),
        ),
        migrations.AlterField(
            model_name='gymcoach',
            name='specialty',
            field=models.CharField(max_length=100, verbose_name='تخصص'),
        ),
        migrations.AlterField(
            model_name='gymfacility',
            name='title',
            field=models.CharField(max_length=100, verbose_name='نام امکانات'),
        ),
        migrations.AlterField(
            model_name='gymimage',
            name='gym',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='gym.gym', verbose_name='باشگاه'),
        ),
        migrations.AlterField(
            model_name='gymimage',
            name='image',
            field=models.ImageField(upload_to='gyms/gallery/', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='gymimage',
            name='title',
            field=models.CharField(blank=True, max_length=100, verbose_name='عنوان تصویر'),
        ),
        migrations.AlterField(
            model_name='gymprice',
            name='gym',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='gym.gym', verbose_name='باشگاه'),
        ),
        migrations.AlterField(
            model_name='gymprice',
            name='monthly_price',
            field=models.PositiveIntegerField(verbose_name='قیمت ماهانه'),
        ),
        migrations.AlterField(
            model_name='gymprice',
            name='quarterly_price',
            field=models.PositiveIntegerField(default=0, verbose_name='قیمت سه ماهه'),
        ),
        migrations.AlterField(
            model_name='gymprice',
            name='session_price',
            field=models.PositiveIntegerField(default=0, verbose_name='قیمت تک جلسه'),
        ),
        migrations.AlterField(
            model_name='gymprice',
            name='sport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym.sport', verbose_name='رشته ورزشی'),
        ),
        migrations.AlterField(
            model_name='gymprice',
            name='yearly_price',
            field=models.PositiveIntegerField(verbose_name='قیمت سالانه'),
        ),
        migrations.AlterField(
            model_name='gymreview',
            name='comment',
            field=models.TextField(verbose_name='نظر'),
        ),
        migrations.AlterField(
            model_name='gymreview',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت'),
        ),
        migrations.AlterField(
            model_name='gymreview',
            name='gym',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='gym.gym', verbose_name='باشگاه'),
        ),
        migrations.AlterField(
            model_name='gymreview',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام کاربر'),
        ),
        migrations.AlterField(
            model_name='gymreview',
            name='rating',
            field=models.PositiveSmallIntegerField(default=5, verbose_name='امتیاز'),
        ),
        migrations.AlterField(
            model_name='gymvideo',
            name='gym',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='gym.gym', verbose_name='باشگاه'),
        ),
        migrations.AlterField(
            model_name='gymvideo',
            name='title',
            field=models.CharField(blank=True, max_length=100, verbose_name='عنوان ویدیو'),
        ),
        migrations.AlterField(
            model_name='gymvideo',
            name='video_url',
            field=models.URLField(verbose_name='لینک ویدیو'),
        ),
        migrations.AlterField(
            model_name='sport',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sports', to='gym.sportcategory', verbose_name='دسته\u200cبندی'),
        ),
        migrations.AlterField(
            model_name='sport',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام رشته ورزشی'),
        ),
        migrations.AlterField(
            model_name='sportcategory',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='اسلاگ'),
        ),
        migrations.AlterField(
            model_name='sportcategory',
            name='title',
            field=models.CharField(max_length=100, verbose_name='عنوان دسته\u200cبندی'),
        ),
    ]
