# Generated by Django 6.0.6 on 2026-07-22 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0005_alter_gym_options_alter_gymbanner_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gymcoach',
            name='sports',
            field=models.ManyToManyField(blank=True, related_name='coaches', to='gym.sport'),
        ),
    ]
