# Generated by Django 6.0.6 on 2026-07-27 09:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gym', '0006_gymcoach_sports'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GymStaffAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'مالک'), ('staff', 'کارمند')], default='owner', max_length=10, verbose_name='نقش')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_accesses', to='gym.gym', verbose_name='باشگاه')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gym_accesses', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'دسترسی باشگاه\u200cدار',
                'verbose_name_plural': 'دسترسی\u200cهای باشگاه\u200cدار',
                'unique_together': {('user', 'gym')},
            },
        ),
    ]
