# Generated by Django 6.0.6 on 2026-07-30 08:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0006_gymcoach_sports'),
        ('gym_panel', '0001_initial'),
        ('tokens', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GymChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('field_edit', 'ویرایش فیلد محدود'), ('new_sport', 'پیشنهاد رشته ورزشی جدید')], max_length=20, verbose_name='نوع درخواست')),
                ('payload', models.JSONField(verbose_name='داده\u200cهای درخواست')),
                ('status', models.CharField(choices=[('pending', 'در انتظار بررسی'), ('approved', 'تایید شده'), ('rejected', 'رد شده')], default='pending', max_length=10, verbose_name='وضعیت')),
                ('admin_note', models.CharField(blank=True, max_length=255, verbose_name='یادداشت ادمین')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ بررسی')),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_requests', to='gym.gym', verbose_name='باشگاه')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gym_change_requests', to=settings.AUTH_USER_MODEL, verbose_name='درخواست\u200cدهنده')),
            ],
            options={
                'verbose_name': 'درخواست تغییر باشگاه',
                'verbose_name_plural': 'درخواست\u200cهای تغییر باشگاه',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GymVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(verbose_name='قیمت (تومان) - در لحظه ثبت')),
                ('source', models.CharField(choices=[('token', 'توکن فیتوپیا'), ('direct', 'ثبت مستقیم باشگاه')], max_length=10, verbose_name='منبع')),
                ('guest_name', models.CharField(blank=True, max_length=150, verbose_name='نام مراجعه\u200cکننده (ثبت مستقیم)')),
                ('guest_phone', models.CharField(blank=True, max_length=15, verbose_name='شماره مراجعه\u200cکننده (ثبت مستقیم)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='gym.gym', verbose_name='باشگاه')),
                ('registered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_visits', to=settings.AUTH_USER_MODEL, verbose_name='ثبت\u200cشده توسط')),
                ('sport', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to='gym.sport', verbose_name='رشته ورزشی')),
                ('token', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visit', to='tokens.gymtoken', verbose_name='توکن مرتبط')),
            ],
            options={
                'verbose_name': 'ورود به باشگاه',
                'verbose_name_plural': 'ورودهای باشگاه',
                'ordering': ['-created_at'],
            },
        ),
    ]
