# Generated by Django 6.0.6 on 2026-08-02 07:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0006_gymcoach_sports'),
        ('gym_panel', '0002_gymchangerequest_gymvisit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GymCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='نام و نام خانوادگی')),
                ('phone', models.CharField(max_length=15, verbose_name='شماره تماس')),
                ('join_date', models.DateField(verbose_name='تاریخ عضویت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('fitopia_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gym_customer_profiles', to=settings.AUTH_USER_MODEL, verbose_name='کاربر فیتوپیا (در صورت وجود)')),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='gym.gym', verbose_name='باشگاه')),
                ('sport', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gym_customers', to='gym.sport', verbose_name='رشته ورزشی')),
            ],
            options={
                'verbose_name': 'مشتری باشگاه',
                'verbose_name_plural': 'مشتریان باشگاه',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GymTicketMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_role', models.CharField(choices=[('gym', 'باشگاه\u200cدار'), ('admin', 'ادمین'), ('system', 'سیستم')], max_length=10, verbose_name='فرستنده')),
                ('message', models.TextField(verbose_name='پیام')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gym_ticket_messages', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='gym_panel.gymchangerequest', verbose_name='تیکت')),
            ],
            options={
                'verbose_name': 'پیام تیکت',
                'verbose_name_plural': 'پیام\u200cهای تیکت',
                'ordering': ['created_at'],
            },
        ),
    ]
