# Generated by Django 6.0.6 on 2026-08-04 19:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_panel', '0003_gymcustomer_gymticketmessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='gymcustomer',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_gym_customers', to=settings.AUTH_USER_MODEL, verbose_name='ثبت\u200cشده توسط (کارمند/باشگاه\u200cدار)'),
        ),
        migrations.AddField(
            model_name='gymcustomer',
            name='price_paid',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='مبلغ پرداختی (تومان)'),
        ),
        migrations.AddField(
            model_name='gymcustomer',
            name='sessions_remaining',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='جلسات باقی\u200cمانده'),
        ),
        migrations.AddField(
            model_name='gymcustomer',
            name='sessions_total',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='تعداد کل جلسات (بسته)'),
        ),
        migrations.AddField(
            model_name='gymcustomer',
            name='source',
            field=models.CharField(choices=[('token', 'توکن/اشتراک فیتوپیا'), ('manual', 'ثبت دستی توسط باشگاه')], default='manual', max_length=10, verbose_name='منبع'),
        ),
    ]
