# Generated by Django 6.0.6 on 2026-08-10 08:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0006_gymcoach_sports'),
        ('gym_panel', '0004_gymcustomer_added_by_gymcustomer_price_paid_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='gymcustomer',
            name='coach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='gym.gymcoach', verbose_name='مربی'),
        ),
        migrations.AddField(
            model_name='gymcustomer',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AddField(
            model_name='gymcustomer',
            name='last_visit_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='آخرین حضور'),
        ),
        migrations.AddField(
            model_name='gymcustomer',
            name='membership_end',
            field=models.DateField(blank=True, null=True, verbose_name='پایان عضویت'),
        ),
        migrations.AddField(
            model_name='gymcustomer',
            name='membership_start',
            field=models.DateField(blank=True, null=True, verbose_name='شروع عضویت'),
        ),
        migrations.AddField(
            model_name='gymcustomer',
            name='membership_status',
            field=models.CharField(choices=[('active', 'فعال'), ('expired', 'منقضی'), ('suspended', 'معلق'), ('inactive', 'غیرفعال')], default='active', max_length=20, verbose_name='وضعیت عضویت'),
        ),
        migrations.AddField(
            model_name='gymcustomer',
            name='membership_type',
            field=models.CharField(blank=True, choices=[('session_pack', 'بسته جلسه'), ('monthly', 'ماهانه'), ('course', 'دوره'), ('single', 'تکی'), ('other', 'سایر')], default='session_pack', max_length=30, verbose_name='نوع عضویت'),
        ),
        migrations.AddField(
            model_name='gymcustomer',
            name='notes',
            field=models.TextField(blank=True, verbose_name='یادداشت'),
        ),
        migrations.AddField(
            model_name='gymcustomer',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/gym/customers/', verbose_name='عکس'),
        ),
        migrations.AddField(
            model_name='gymcustomer',
            name='sessions_used',
            field=models.PositiveIntegerField(default=0, verbose_name='جلسات مصرف‌شده'),
        ),
        migrations.AddField(
            model_name='gymstaffaccess',
            name='employee_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='کد پرسنلی'),
        ),
        migrations.AddField(
            model_name='gymstaffaccess',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ پایان'),
        ),
        migrations.AddField(
            model_name='gymstaffaccess',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AddField(
            model_name='gymstaffaccess',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ شروع'),
        ),
        migrations.AddField(
            model_name='gymvisit',
            name='check_in_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان ورود'),
        ),
        migrations.AddField(
            model_name='gymvisit',
            name='check_out_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان خروج'),
        ),
        migrations.AddField(
            model_name='gymvisit',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to='gym_panel.gymcustomer', verbose_name='مشتری'),
        ),
        migrations.AddField(
            model_name='gymvisit',
            name='is_open',
            field=models.BooleanField(default=False, verbose_name='حضور فعال'),
        ),
        migrations.AddField(
            model_name='gymvisit',
            name='method',
            field=models.CharField(blank=True, choices=[('qr', 'QR'), ('token', 'توکن'), ('manual', 'دستی'), ('membership', 'عضویت')], default='manual', max_length=20, verbose_name='روش ثبت'),
        ),
        migrations.AlterField(
            model_name='gymstaffaccess',
            name='role',
            field=models.CharField(choices=[('owner', 'مالک'), ('manager', 'مدیر'), ('receptionist', 'پذیرش'), ('accountant', 'حسابدار'), ('coach', 'مربی'), ('staff', 'کارمند')], default='owner', max_length=20, verbose_name='نقش'),
        ),
        migrations.AlterField(
            model_name='gymvisit',
            name='price',
            field=models.IntegerField(default=0, verbose_name='قیمت (تومان) - در لحظه ثبت'),
        ),
        migrations.AlterField(
            model_name='gymvisit',
            name='source',
            field=models.CharField(choices=[('token', 'توکن فیتوپیا'), ('direct', 'ثبت مستقیم باشگاه'), ('qr', 'QR'), ('manual', 'دستی'), ('membership', 'عضویت'), ('single_session', 'جلسه تکی')], max_length=20, verbose_name='منبع'),
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('days_of_week', models.CharField(blank=True, help_text='مثلاً 0,2,4 برای شنبه/دوشنبه/چهارشنبه', max_length=50)),
                ('capacity', models.PositiveIntegerField(default=20)),
                ('price', models.PositiveIntegerField(help_text='تومان')),
                ('status', models.CharField(choices=[('draft', 'پیش‌نویس'), ('open', 'باز'), ('full', 'تکمیل ظرفیت'), ('closed', 'بسته'), ('cancelled', 'لغو شده')], default='open', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='gym.gymcoach')),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='gym.gym')),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='gym.sport')),
            ],
            options={
                'verbose_name': 'دوره',
                'verbose_name_plural': 'دوره‌ها',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='FinanceTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('income', 'درآمد'), ('expense', 'هزینه')], max_length=10)),
                ('category', models.CharField(choices=[('membership', 'عضویت'), ('course', 'دوره'), ('single_session', 'جلسه تکی'), ('other_income', 'سایر درآمد'), ('rent', 'اجاره'), ('utilities', 'قبوض'), ('equipment', 'تجهیزات'), ('salary', 'حقوق'), ('coach_payment', 'پرداخت مربی'), ('maintenance', 'نگهداری'), ('marketing', 'بازاریابی'), ('other_expense', 'سایر هزینه')], max_length=30)),
                ('amount', models.PositiveIntegerField(help_text='مبلغ به تومان (صحیح)')),
                ('date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('payment_method', models.CharField(choices=[('cash', 'نقد'), ('card', 'کارت'), ('transfer', 'کارت به کارت'), ('online', 'آنلاین'), ('other', 'سایر')], default='cash', max_length=20)),
                ('reference_number', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('completed', 'تکمیل'), ('pending', 'در انتظار'), ('cancelled', 'لغو'), ('refunded', 'مسترد')], default='completed', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='gym_panel.course')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_transactions', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='gym_panel.gymcustomer')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_transactions', to=settings.AUTH_USER_MODEL)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='gym.gym')),
            ],
            options={
                'verbose_name': 'تراکنش مالی',
                'verbose_name_plural': 'تراکنش‌های مالی',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.PositiveIntegerField(help_text='مبلغ کل تومان')),
                ('amount_paid', models.PositiveIntegerField(default=0, help_text='پرداخت‌شده تومان')),
                ('discount', models.PositiveIntegerField(default=0, help_text='تخفیف تومان')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('payment_method', models.CharField(choices=[('cash', 'نقد'), ('card', 'کارت'), ('transfer', 'کارت به کارت'), ('online', 'آنلاین'), ('other', 'سایر')], default='cash', max_length=20)),
                ('reference_number', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='gym_panel.gymcustomer')),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_payments', to='gym.gym')),
                ('related_course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gym_panel.course')),
                ('related_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gym_panel.financetransaction')),
            ],
            options={
                'verbose_name': 'پرداخت مشتری',
                'verbose_name_plural': 'پرداخت‌های مشتری',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GymOffering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('single_session_price', models.PositiveIntegerField(blank=True, help_text='تومان', null=True)),
                ('course_price', models.PositiveIntegerField(blank=True, help_text='تومان', null=True)),
                ('monthly_price', models.PositiveIntegerField(blank=True, help_text='تومان', null=True)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('skill_level', models.CharField(choices=[('beginner', 'مبتدی'), ('intermediate', 'متوسط'), ('advanced', 'پیشرفته'), ('all', 'همه سطوح')], default='all', max_length=20)),
                ('gender_restriction', models.CharField(choices=[('all', 'همه'), ('male', 'آقایان'), ('female', 'بانوان')], default='all', max_length=10)),
                ('min_age', models.PositiveIntegerField(blank=True, null=True)),
                ('max_age', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coaches', models.ManyToManyField(blank=True, related_name='offerings', to='gym.gymcoach')),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offerings', to='gym.gym')),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gym_offerings', to='gym.sport')),
            ],
            options={
                'verbose_name': 'ارائه رشته در باشگاه',
                'verbose_name_plural': 'ارائه‌های رشته در باشگاه',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='offering',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='gym_panel.gymoffering'),
        ),
        migrations.CreateModel(
            name='GymOfferingSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.PositiveSmallIntegerField(choices=[(0, 'شنبه'), (1, 'یکشنبه'), (2, 'دوشنبه'), (3, 'سه‌شنبه'), (4, 'چهارشنبه'), (5, 'پنجشنبه'), (6, 'جمعه')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='gym_panel.gymoffering')),
            ],
            options={
                'verbose_name': 'برنامه زمانی رشته',
                'verbose_name_plural': 'برنامه‌های زمانی رشته',
                'ordering': ['day_of_week', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(help_text='تومان')),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('approved', 'تایید'), ('rejected', 'رد'), ('completed', 'انجام‌شده')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='gym.gym')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('original_transaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='gym_panel.financetransaction')),
            ],
            options={
                'verbose_name': 'استرداد',
                'verbose_name_plural': 'استردادها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SingleSessionPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField(help_text='تومان')),
                ('status', models.CharField(choices=[('unused', 'استفاده‌نشده'), ('used', 'استفاده‌شده'), ('expired', 'منقضی'), ('cancelled', 'لغو')], default='unused', max_length=20)),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='single_sessions', to='gym_panel.gymcustomer')),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='single_sessions', to='gym.gym')),
                ('sport', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gym.sport')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='single_sessions', to='gym_panel.financetransaction')),
            ],
            options={
                'verbose_name': 'جلسه تکی',
                'verbose_name_plural': 'جلسات تکی',
                'ordering': ['-purchased_at'],
            },
        ),
        migrations.CreateModel(
            name='StaffPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('customer.view', 'مشاهده مشتری'), ('customer.create', 'ایجاد مشتری'), ('customer.update', 'ویرایش مشتری'), ('customer.delete', 'حذف مشتری'), ('course.view', 'مشاهده دوره'), ('course.create', 'ایجاد دوره'), ('course.update', 'ویرایش دوره'), ('course.enroll', 'ثبت‌نام در دوره'), ('attendance.view', 'مشاهده حضور'), ('attendance.create', 'ثبت حضور'), ('finance.view', 'مشاهده مالی'), ('finance.create', 'ثبت مالی'), ('finance.update', 'ویرایش مالی'), ('finance.report', 'گزارش مالی'), ('finance.refund', 'استرداد'), ('employee.view', 'مشاهده کارمند'), ('employee.manage', 'مدیریت کارمند'), ('offering.manage', 'مدیریت رشته‌ها')], max_length=40)),
                ('staff_access', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='gym_panel.gymstaffaccess')),
            ],
            options={
                'verbose_name': 'مجوز کارمند',
                'verbose_name_plural': 'مجوزهای کارمند',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('object_type', models.CharField(blank=True, max_length=80)),
                ('object_id', models.CharField(blank=True, max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gym', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='gym.gym')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'لاگ حسابرسی',
                'verbose_name_plural': 'لاگ‌های حسابرسی',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['gym', '-created_at'], name='gym_panel_a_gym_id_0f094a_idx')],
            },
        ),
        migrations.CreateModel(
            name='CourseEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'فعال'), ('completed', 'تمام‌شده'), ('cancelled', 'لغو')], default='active', max_length=20)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('price_paid', models.PositiveIntegerField(default=0, help_text='تومان')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='gym_panel.course')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='gym_panel.gymcustomer')),
            ],
            options={
                'verbose_name': 'ثبت‌نام دوره',
                'verbose_name_plural': 'ثبت‌نام‌های دوره',
                'unique_together': {('course', 'customer')},
            },
        ),
        migrations.AddIndex(
            model_name='financetransaction',
            index=models.Index(fields=['gym', 'date'], name='gym_panel_f_gym_id_53465d_idx'),
        ),
        migrations.AddIndex(
            model_name='financetransaction',
            index=models.Index(fields=['gym', 'type'], name='gym_panel_f_gym_id_d9a614_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='gymoffering',
            unique_together={('gym', 'sport')},
        ),
        migrations.AlterUniqueTogether(
            name='staffpermission',
            unique_together={('staff_access', 'code')},
        ),
    ]
