# Generated by Django 6.0.6 on 2026-06-25 08:15

import django.db.models.deletion
import tokens.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gym', '0005_alter_gym_options_alter_gymbanner_options_and_more'),
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GymToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='کد توکن')),
                ('status', models.CharField(choices=[('active', 'فعال'), ('used', 'استفاده\u200cشده'), ('expired', 'منقضی\u200cشده')], default='active', max_length=20, verbose_name='وضعیت')),
                ('issued_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان صدور')),
                ('valid_until', models.DateTimeField(default=tokens.models.default_valid_until, verbose_name='اعتبار تا')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان استفاده')),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='gym.gym', verbose_name='باشگاه')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gym_tokens', to='subscriptions.usersubscription', verbose_name='اشتراک')),
            ],
            options={
                'verbose_name': 'توکن باشگاه',
                'verbose_name_plural': 'توکن\u200cهای باشگاه',
                'ordering': ['-issued_at'],
            },
        ),
    ]
